### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Kepler-16b** [KohakuBlueleaf/a1111-sd-webui-lycoris#1]
I moved some LyCORIS into the folder with their preview images, and the console throw out this error. The preview images were synced by civitai-helper. And I created subfolders inside the LyCORIS folder. What can I do to fix this error?

```
Traceback (most recent call last):
  File "K:\stable-diffusion-webui\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "K:\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\stable-diffusion-webui\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "K:\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "K:\stable-diffusion-webui\modules\ui_extra_networks.py", line 204, in refresh
    res.append(pg.create_html(ui.tabname))
  File "K:\stable-diffusion-webui\modules\ui_extra_networks.py", line 94, in create_html
    for item in self.list_items():
  File "K:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\ui_extra_networks_lyco.py", line 21, in list_items
    "preview": self.find_preview(path),
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'find_preview'
```

**Comment by KohakuBlueleaf** [comment]
What's your sd-webui's commit?

**Comment by Kepler-16b** [comment]
> What's your sd-webui's commit?

[0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)

**Comment by Kepler-16b** [comment]
> @Kepler-16b You should use sd-webui commit >= ce68ab8

Alright. But which commit do you recommend? because I've updated two weeks ago, and it broke most of my extexsions. I'm not quite sure which one is the stable one :(

**Comment by KohakuBlueleaf** [comment]
There is not stable one
it depends on what extensino you are using
some extension just never catch up new update
some extension always catch up new update

For myself, I always use latest one to develop my extension

**Comment by Kepler-16b** [comment]
> There is not stable one it depends on what extensino you are using some extension just never catch up new update some extension always catch up new update
> 
> For myself, I always use latest one to develop my extension

well that's too bad. Gues I'll just have to try different commits. Thanks.
