### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by TricksyZerg** [KohakuBlueleaf/a1111-sd-webui-lycoris#11]
Error loading script: lycoris_script.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/scripts/lycoris_script.py", line 4, in <module>
    import lycoris
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/lycoris.py", line 786, in <module>
    list_available_lycos()
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/lycoris.py", line 767, in list_available_lycos
    os.makedirs(shared.cmd_opts.lyco_dir, exist_ok=True)
AttributeError: 'Namespace' object has no attribute 'lyco_dir'

**Comment by TricksyZerg** [comment]
it's working after restarting the script
