### ISSUE TITLE
Having this error every time I'm using a Lora/Lycoris:

### ISSUE THREAD

**Issue by GastonSan79** [KohakuBlueleaf/a1111-sd-webui-lycoris#13]
`activating extra network lyco with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000002483580B0D0>, <modules.extra_networks.ExtraNetworkParams object at 0x000002483580B580>]: TypeError
Traceback (most recent call last):
  File "H:\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "H:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 61, in activate
    te, unet, dyn_dim = parse_args(params.items[1:])
  File "H:\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 17, in parse_args
    if '=' in i:
TypeError: argument of type 'float' is not iterable`

-Commit: [22bcc7be]
(https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
-Extension up to date

I'm really lost here. Any help or guidance will be welcomed.

**Comment by KohakuBlueleaf** [comment]
@GastonSan79 I pushed a fix for this issue, plz check it.
