### ISSUE TITLE
activating extra network lyco: AttributeError

### ISSUE THREAD

**Issue by acergelff** [KohakuBlueleaf/a1111-sd-webui-lycoris#23]
activating extra network lyco: AttributeError
Traceback (most recent call last):
  File "C:\Users\XXX\stable-diffusion-webui\modules\extra_networks.py", line 85, in activate
    extra_network.activate(p, [])
  File "C:\Users\XXX\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 41, in activate
    additional = shared.opts.sd_lyco
  File "C:\Users\XXX\stable-diffusion-webui\modules\shared.py", line 493, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'sd_lyco'

I got an error when generating images after I pulled the new version of webui today (and updated all the plugins).

**Comment by jamesofarrell** [comment]
You can fix this by added "--xformers" to your COMMANDLINE_ARGS in webui-user

**Comment by KohakuBlueleaf** [comment]
You need to use cool reboot instead of "apply and restart"
