### ISSUE TITLE
不知爲何更新之後lyco模型再也加載不出，之前還是可以的

### ISSUE THREAD

**Issue by ManulPoly** [KohakuBlueleaf/a1111-sd-webui-lycoris#26]

**Comment by lzardy** [comment]
Translation: LoRA cannot be loaded after recent updates.

**Comment by fadedninna** [comment]
please update!

**Comment by TengPan2011** [comment]
Exact error message
ating extra network lyco with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001D2BF420E50>]: TypeError
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\SD\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 69, in activate
    te, unet, dyn_dim = parse_args(params.items[1:])
  File "D:\SD\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\extra_networks_lyco.py", line 35, in parse_args
    x = type(x)
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by KohakuBlueleaf** [comment]
@TengPan2011 Your error should be fixed, plz check latest commit

**Comment by KohakuBlueleaf** [comment]
@ManulPoly 如果沒有任何錯誤訊息/額外訊息的話，比較有可能的是你的sd-webui並沒有正確載入插件。
