### ISSUE TITLE
Error when installing webui lycoris

### ISSUE THREAD

**Issue by NeiliChan** [KohakuBlueleaf/a1111-sd-webui-lycoris#28]
This error keeps appearing after restarting ui or opening webui user

Traceback (most recent call last):
  File "G:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\stable-diffusion\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\scripts\lycoris_script.py", line 4, in <module>
    import lycoris
  File "G:\stable-diffusion\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 795, in <module>
    list_available_lycos()
  File "G:\stable-diffusion\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 776, in list_available_lycos
    os.makedirs(shared.cmd_opts.lyco_dir, exist_ok=True)
AttributeError: 'Namespace' object has no attribute 'lyco_dir'

**Comment by Ainaemaet** [comment]
Similar error here: 

Error loading script: lycoris_script.py
Traceback (most recent call last):
  File "/mnt/q/MLEARN/img/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/mnt/q/MLEARN/img/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/q/MLEARN/img/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/scripts/lycoris_script.py", line 4, in <module>
    import lycoris
  File "/mnt/q/MLEARN/img/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/lycoris.py", line 795, in <module>
    list_available_lycos()
  File "/mnt/q/MLEARN/img/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/lycoris.py", line 776, in list_available_lycos
    os.makedirs(shared.cmd_opts.lyco_dir, exist_ok=True)
AttributeError: 'Namespace' object has no attribute 'lyco_dir'

I'm getting a bunch of them though for various extensions since the last update...

**Comment by KohakuBlueleaf** [comment]
after install the extension, you need to "reboot" the webui process.
Not "Apply and Restart" that will not restart your webui process.
