### ISSUE TITLE
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'

### ISSUE THREAD

**Issue by pixielova** [KohakuBlueleaf/a1111-sd-webui-lycoris#47]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
 I had this problem today while trying to run SD through google colab.

Traceback (most recent call last):
  File "/content//stable-diffusion-webui/launch.py", line 383, in <module>
    start()
  File "/content//stable-diffusion-webui/launch.py", line 377, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui()
  File "/content/stable-diffusion-webui/modules/ui.py", line 468, in create_ui
    extra_networks_ui = ui_extra_networks.create_ui(extra_networks, extra_networks_button, 'txt2img')
  File "/content/stable-diffusion-webui/modules/ui_extra_networks.py", line 218, in create_ui
    page_elem = gr.HTML(page.create_html(ui.tabname))
  File "/content/stable-diffusion-webui/modules/ui_extra_networks.py", line 94, in create_html
    for item in self.list_items():
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/ui_extra_networks_lyco.py", line 33, in list_items
    "sort_keys": {'default': index, **self.get_sort_keys(lyco_on_disk.filename)},
AttributeError: 'ExtraNetworksPageLyCORIS' object has no attribute 'get_sort_keys'

**Comment by cuffuuguu** [comment]
What is your version of lycoris extension?

I believe this bug has been fixed in 21e9ea0f58dfdbee12b08389fd2cd1aa545e058.

**Comment by KohakuBlueleaf** [comment]
This issue already be resolved.
I will close this issue.
