### ISSUE TITLE
Lycoris not loading in Automatic1111

### ISSUE THREAD

**Issue by david9039** [KohakuBlueleaf/a1111-sd-webui-lycoris#49]
Lycoris is not loading when Automatic1111 is started.  Tried reinstalling, but got the same error.

Error loading script: lycoris_script.py
Traceback (most recent call last):
  File "C:\Users\parso\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\parso\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\parso\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\scripts\lycoris_script.py", line 7, in <module>
    from lyco_logger import logger
  File "C:\Users\parso\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lyco_logger.py", line 10, in <module>
    if shared.cmd_opts.lyco_debug:
AttributeError: 'Namespace' object has no attribute 'lyco_debug'

**Comment by Proquror** [comment]
I got that one too after the update

**Comment by MichaelDeathBringer** [comment]
Yea I got the same one, how do I fix this?

**Comment by roll0ver** [comment]
Same error here

**Comment by KohakuBlueleaf** [comment]
should be fixed
